# Generated by Django 4.2.8 on 2024-09-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
    ]
